config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'pages#home'
  get 'about', to: 'pages#about'
  resources :articles
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
    validates :title, presence: true, length: { minimum: 5, maximum: 100 }
    validates :description, presence: true, length: { minimum: 10 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    def hello
        render html: 'Hello World!'
    end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
    def show
        @article = Article.find(params[:id])
    end
    
    def index
        @articles = Article.all
    end
    
    def new
        @article = Article.new
    end
    
    def edit
        @article = Article.find(params[:id])
    end

    def create
        @article = Article.new(params.require(:article).permit(:title, :description))
        if @article.save
            flash[:notice] = "Article was created sucessfully."
            redirect_to @article
        else
            render 'new'
        end
    end

    def update
        @article = Article.find(params[:id])
        if @article.update(params.require(:article).permit(:title, :description))
            flash[:notice] = "Article was updated sucessfully"
            redirect_to @article
        else
            render 'edit'
        end
    end
    
    def destroy
        @article = Article.find(params[:id])
        @article.destroy
        redirect_to articles_path
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    def home
        
    end
    
    def about
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/articles/edit.html.erb
<h1>Edit article</h1>

<% if @article.errors.any? %>
    <h2> The following errors prevented the article from being save </h2>
    <% @article.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
    <% end %>
<% end %>

<%= form_with(model: @article, local: true) do |f| %>
    <p>
        <%= f.label :title %></br>
        <%= f.text_field :title %>
    </p>
    <p>
        <%= f.label :description %></br>
        <%= f.text_area :description %>
    </p>
    <p>
        <%= f.submit %></br>
    </p>
<% end %>
<%= link_to 'Cancel and return to articles list', articles_path %>

app/views/articles/index.html.erb
<h1>Articles list page</h1>

<table>
    <thead>
        <tr>
            <th> Title </th>
            <th> Description </th>
            <th colspan="3"> Actions </th>
        </tr>
    </thead>
    <tbody>
        <% @articles.each do |article| %>
        <tr>
            <td><%= article.title %></td>
            <td><%= article.description %></td>
            <td><%= link_to 'Show', article_path(article) %></td>
            <td><%= link_to 'Edit', edit_article_path(article) %></td>
            <td><%= link_to 'Delete', article_path(article), method: :delete, data: { confirm: "Are you sure?" } %></td>
        </tr>
        <% end %>
    </tbody>
</table>
<p><%= link_to 'Create new article', new_article_path %></p>

app/views/articles/new.html.erb
<h1>Create a new article</h1>

<% if @article.errors.any? %>
    <h2> The following errors prevented the article from being save </h2>
    <% @article.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
    <% end %>
<% end %>

<%= form_with scope: :article, url: articles_path, local: true do |f| %>
    <p>
        <%= f.label :title %></br>
        <%= f.text_field :title %>
    </p>
    <p>
        <%= f.label :description %></br>
        <%= f.text_area :description %>
    </p>
    <p>
        <%= f.submit %></br>
    </p>
<% end %>
<%= link_to 'Return to articles list', articles_path %>

app/views/articles/show.html.erb
<h1>Showing article details</h1>
<p><strong>Title: </strong><%= @article.title %></p>
<p><strong>Description: </strong><%= @article.description %></p>
<%= link_to 'Edit', edit_article_path(@article) %> | 
<%= link_to 'Delete', article_path(@article), method: :delete, data: { confirm: "Are you sure?" } %> | 
<%= link_to 'Return to articles list', articles_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FirstApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% flash.each do |name, msg| %>
      <%= msg %>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/pages/about.html.erb
<h1>This is the about page</h1>

<%= link_to 'Articles list', articles_path %> |
<%= link_to 'Home page', root_path %>

app/views/pages/home.html.erb
<h1>This is the Home Page!</h1>

<%= link_to 'Articles list', articles_path %> |
<%= link_to 'About page', about_path %>